ELearning/Source/ELearning/Controllers/CourseController.cs
using BELibrary.Core.Entity;
using BELibrary.Entity;
using BELibrary.Utils;
using ELearning.Handler;
using ELearning.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ELearning.Controllers
{
    public class CourseController : Controller
    {
        // GET: Course
        public ActionResult Index(int? page)
        {
            using (var unitofwork = new UnitOfWork(new ELearningDBContext()))
            {
                var related = unitofwork.Courses.GetAll().OrderByDescending(x => x.ModifiedDate).Take(3).ToList();
                ViewBag.Related = related;

                var items = unitofwork.Courses.GetAll().Select(x => new CourseDto
                {
                    Id = x.Id,
                    Name = x.Name,
                    Image = x.Image,
                    Description = x.Description,
                });

                int pageNumber = (page ?? 1);
                int pageSize = 12;
                var result = items.ToPagedList(pageNumber, pageSize);

                foreach (var item in result)
                {
                    item.Rate = unitofwork.Rating.CalculatorRate(item.Id).Total * 2 * 10;
                }

                return View(result);
            }
        }

        public ActionResult Detail(int? id, int? page)
        {
            if (!id.HasValue)
            {
                return Redirect("/Home/e404");
            }
            using (var unitofwork = new UnitOfWork(new ELearningDBContext()))
            {
                var item = unitofwork.Courses.FirstOrDefault(x => x.Id == id);
                var baihoc = unitofwork.Lectures.FirstOrDefault(x => x.Id == id);
                if (item == null)
                {
                    return Redirect("/Home/e404");
                }
                ViewBag.Rate = unitofwork.Rating.CalculatorRate(item.Id);

                double rateByUser = 0;
                if (CookiesManage.Logined())
                {
                    var user = CookiesManage.GetUser();
                    var rating = unitofwork.Rating.FirstOrDefault(x => x.CourseId == item.Id && x.Username == user.Username);
                    if (rating != null)
                    {
                        rateByUser = rating.Point;
                    }
                }

                NumberFormatInfo nfi = new NumberFormatInfo
                {
                    NumberDecimalSeparator = "."
                };

                ViewBag.RateByUser = rateByUser.ToString(nfi);

                var subjects = unitofwork.Subjects.Query(x => x.CourseId == id).ToList();

                int pageNumber = (page ?? 1);
                int pageSize = 6;

                ViewBag.Item = item;
                //result.MOTAFULL = result.MOTAFULL.Replace("#", "<br/>");    //thay thế # bằng <br/> trong bảng mô tả khóa học
                //result.MUCTIEU = result.MUCTIEU.Replace("#", "<br/>");      //thay thế # bằng <br/> trong bảng mục tiêu khóa học       

                return View(subjects.ToPagedList(pageNumber, pageSize));
            }
        }

        [HttpPost]
        [ValidateInput(true)]
        public JsonResult Rate(int courseId, double point)
        {
            if (CookiesManage.Logined())
            {
                if (courseId >= 1 && RateKey.Any(point))
                {
                    using (var unitofwork = new UnitOfWork(new ELearningDBContext()))
                    {
                        var user = CookiesManage.GetUser();
                        var course = unitofwork.Courses.FirstOrDefault(x => x.Id == courseId);
                        if (course != null)
                        {
                            var rating = unitofwork.Rating.FirstOrDefault(x => x.CourseId == courseId && x.Username == user.Username);

                            if (rating != null)
                            {
                                rating.Point = point;
                                unitofwork.Rating.Put(rating, rating.Id);
                            }
                            else
                            {
                                var rate = new Rating
                                {
                                    CourseId = course.Id,
                                    Username = CookiesManage.GetUser().Username,
                                    Point = point
                                };
                                unitofwork.Rating.Add(rate);
                            }

                            unitofwork.Complete();
                            //xóa thành công
                            return Json(new { status = true, mess = $"Bạn đã xếp hạng: {point} sao cho khóa học: {course.Name}" });
                        }
                        else
                        {
                            return Json(new { status = false, mess = "course không tồn tại" });
                        }
                    }
                }
                else
                {
                    return Json(new { status = false, mess = "Lỗi dữ liệu" });
                }
            }
            else
            {
                return Json(new { status = false, mess = "Vui lòng đăng nhập" });
            }
        }

        public ActionResult Search(string keyword, int? page)
        {
            if (keyword == "")
            {
                keyword = null;
            }
            using (var workScope = new UnitOfWork(new ELearningDBContext()))
            {
                var listData = workScope.Courses.Query(x => x.Status).OrderByDescending(x => x.ModifiedDate).ToList();
                var q = from mt in listData
                        where (!string.IsNullOrEmpty(keyword) && mt.Name.ToLower().Contains(keyword.ToLower()))
                              || (!string.IsNullOrEmpty(keyword) && mt.Description.ToLower().Contains(keyword.ToLower()))
                              || (!string.IsNullOrEmpty(keyword) && mt.Content.ToLower().Contains(keyword.ToLower()))
                              || (!string.IsNullOrEmpty(keyword) && mt.Requirements.ToLower().Contains(keyword.ToLower()))
                              || (!string.IsNullOrEmpty(keyword) && mt.Benefits.ToLower().Contains(keyword.ToLower()))
                        select mt;

                var related = workScope.Courses.GetAll().OrderByDescending(x => x.ModifiedDate).Take(3).ToList();
                ViewBag.Related = related;

                var items = q.Select(x => new CourseDto
                {
                    Id = x.Id,
                    Name = x.Name,
                    Image = x.Image,
                    Description = x.Description,
                });

                var pageNumber = (page ?? 1);
                const int pageSize = 4;
                var result = items.ToPagedList(pageNumber, pageSize);

                foreach (var item in result)
                {
                    item.Rate = workScope.Rating.CalculatorRate(item.Id).Total * 2 * 10;
                }
                return View(result);
            }
        }
    }
}

ELearning/Source/ELearning/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html dir="ltr" lang="en">

<head>

    <!-- Meta Tags -->
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta name="description" content="StudyPress | Education & Courses HTML Template" />
    <meta name="keywords" content="academy, course, education, education html theme, elearning, learning," />
    <meta name="author" content="ThemeMascot" />

    <!-- Page Title -->
    <title>@ViewBag.Title</title>

    <!-- Favicon and Touch Icons -->
    <link href="~/Content/images/logo.png" rel="shortcut icon" type="image/png">
    <link href="~/Content/images/logo.png" rel="logo">
    <link href="~/Content/images/logo.png" rel="logo" sizes="72x72">
    <link href="~/Content/images/logo.png" rel="logo" sizes="114x114">
    <link href="~/Content/images/logo.png" rel="logo" sizes="144x144">
    <!-- Stylesheet -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="~/Content/css/jquery-ui.min.css" rel="stylesheet" type="text/css">
    <link href="~/Content/css/animate.css" rel="stylesheet" type="text/css">
    <link href="~/Content/css/css-plugin-collections.css" rel="stylesheet" />
    <!-- CSS | menuzord megamenu skins -->
    <link id="menuzord-menu-skins" href="~/Content/css/menuzord-skins/menuzord-rounded-boxed.css" rel="stylesheet" />
    <!-- CSS | Main style file -->
    <link href="~/Content/css/style-main.css" rel="stylesheet" type="text/css">
    <!-- CSS | Preloader Styles -->
    <link href="~/Content/css/preloader.css" rel="stylesheet" type="text/css">
    <!-- CSS | Custom Margin Padding Collection -->
    <link href="~/Content/css/custom-bootstrap-margin-padding.css" rel="stylesheet" type="text/css">
    <!-- CSS | Responsive media queries -->
    <link href="~/Content/css/responsive.css" rel="stylesheet" type="text/css">
    <!-- CSS | Style css. This is the file where you can place your own custom css code. Just uncomment it and use it. -->
    <!-- <link href="css/style.css" rel="stylesheet" type="text/css"> -->
    <!-- Revolution Slider 5.x CSS settings -->
    <link href="~/Content/js/revolution-slider/css/settings.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/js/revolution-slider/css/layers.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/js/revolution-slider/css/navigation.css" rel="stylesheet" type="text/css" />

    <!-- CSS | Theme Color -->
    <link href="~/Content/css/colors/theme-skin-color-set-1.css" rel="stylesheet" type="text/css">

    <!-- external javascripts -->
    <script src="~/Content/js/jquery-2.2.4.min.js"></script>
    <script src="~/Content/js/jquery-ui.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <!-- JS | jquery plugin collection for this theme -->
    <script src="~/Content/js/jquery-plugin-collection.js"></script>

    <!-- Revolution Slider 5.x SCRIPTS -->
    <script src="~/Content/js/revolution-slider/js/jquery.themepunch.tools.min.js"></script>
    <script src="~/Content/js/revolution-slider/js/jquery.themepunch.revolution.min.js"></script>

    <link href="~/Content/js/bootstrap-rating/bootstrap-rating.css" rel="stylesheet" />
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body class="">
    <div id="wrapper" class="clearfix">
        <!-- preloader -->
        @*<div id="preloader">
            <div id="spinner">
                <div class="preloader-dot-loading">
                    <div class="cssload-loading"><i></i><i></i><i></i><i></i></div>
                </div>
            </div>
            <div id="disable-preloader" class="btn btn-default btn-sm">Disable Preloader</div>
        </div>*@

        <!-- Header -->
        @Html.Partial("_PartialHeader")

        <!-- Start main-content -->
        @RenderBody()

        <!-- Footer -->
        @Html.Partial("_PartialFooter")
        <a class="scrollToTop" href="#"><i class="fa fa-angle-up"></i></a>
    </div>
    <!-- end wrapper -->
    <!-- Footer Scripts -->
    <!-- JS | Custom script for all pages -->
    <script src="~/Content/js/custom.js"></script>

    <!-- SLIDER REVOLUTION 5.0 EXTENSIONS
        (Load Extensions only on Local File Systems !The following part can be removed on Server for On Demand Loading) -->
    <script type="text/javascript" src="~/Content/js/revolution-slider/js/extensions/revolution.extension.actions.min.js"></script>
    <script type="text/javascript" src="~/Content/js/revolution-slider/js/extensions/revolution.extension.carousel.min.js"></script>
    <script type="text/javascript" src="~/Content/js/revolution-slider/js/extensions/revolution.extension.kenburn.min.js"></script>
    <script type="text/javascript" src="~/Content/js/revolution-slider/js/extensions/revolution.extension.layeranimation.min.js"></script>
    <script type="text/javascript" src="~/Content/js/revolution-slider/js/extensions/revolution.extension.migration.min.js"></script>
    <script type="text/javascript" src="~/Content/js/revolution-slider/js/extensions/revolution.extension.navigation.min.js"></script>
    <script type="text/javascript" src="~/Content/js/revolution-slider/js/extensions/revolution.extension.parallax.min.js"></script>
    <script type="text/javascript" src="~/Content/js/revolution-slider/js/extensions/revolution.extension.slideanims.min.js"></script>
    <script type="text/javascript" src="~/Content/js/revolution-slider/js/extensions/revolution.extension.video.min.js"></script>
    <script src="~/Content/js/bootstrap-rating/bootstrap-rating.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ELearning/Source/ELearning/Views/Shared/_LayoutKhoaHoc.cshtml
<!DOCTYPE html>
<html dir="ltr" lang="en">

<head>

    <!-- Meta Tags -->
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta name="description" content="StudyPress | Education & Courses HTML Template" />
    <meta name="keywords" content="academy, course, education, education html theme, elearning, learning," />
    <meta name="author" content="ThemeMascot" />

    <!-- Page Title -->
    <title>@ViewBag.Title</title>

    <!-- Favicon and Touch Icons -->
    <link href="~/Content/images/logo.png" rel="shortcut icon" type="image/png">
    <link href="~/Content/images/logo.png" rel="logo">
    <link href="~/Content/images/logo.png" rel="logo" sizes="72x72">
    <link href="~/Content/images/logo.png" rel="logo" sizes="114x114">
    <link href="~/Content/images/logo.png" rel="logo" sizes="144x144">
    <!-- Stylesheet -->
    @*<link href="~/Content/css/jquery-ui.min.css" rel="stylesheet" type="text/css">*@
    @*<link href="~/Content/css/animate.css" rel="stylesheet" type="text/css">*@
    <link href="~/Content/css/css-plugin-collections.css" rel="stylesheet" />
    <!-- CSS | menuzord megamenu skins -->
    <link id="menuzord-menu-skins" href="~/Content/css/menuzord-skins/menuzord-rounded-boxed.css" rel="stylesheet" />
    <!-- CSS | Main style file -->
    <link href="~/Content/css/style-main.css" rel="stylesheet" type="text/css">
    <!-- CSS | Preloader Styles -->
    <link href="~/Content/css/preloader.css" rel="stylesheet" type="text/css">
    <!-- CSS | Custom Margin Padding Collection -->
    <link href="~/Content/css/custom-bootstrap-margin-padding.css" rel="stylesheet" type="text/css">
    <!-- CSS | Responsive media queries -->
    <link href="~/Content/css/responsive.css" rel="stylesheet" type="text/css">
    <!-- CSS | Style css. This is the file where you can place your own custom css code. Just uncomment it and use it. -->
    <!-- <link href="css/style.css" rel="stylesheet" type="text/css"> -->
    <!-- Revolution Slider 5.x CSS settings -->
    <link href="~/Content/js/revolution-slider/css/settings.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/js/revolution-slider/css/layers.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/js/revolution-slider/css/navigation.css" rel="stylesheet" type="text/css" />

    <!-- CSS | Theme Color -->
    <link href="~/Content/css/colors/theme-skin-color-set-1.css" rel="stylesheet" type="text/css">

    <!-- external javascripts -->
    <script src="~/Content/js/jquery-2.2.4.min.js"></script>
    <script src="~/Content/js/jquery-ui.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <!-- JS | jquery plugin collection for this theme -->
    <script src="~/Content/js/jquery-plugin-collection.js"></script>

    <!-- Revolution Slider 5.x SCRIPTS -->
    <script src="~/Content/js/revolution-slider/js/jquery.themepunch.tools.min.js"></script>
    <script src="~/Content/js/revolution-slider/js/jquery.themepunch.revolution.min.js"></script>

    <link href="~/Content/js/bootstrap-rating/bootstrap-rating.css" rel="stylesheet" />
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body class="">
    <div id="wrapper" class="clearfix">
        <!-- preloader -->
        @*<div id="preloader">
                <div id="spinner">
                    <div class="preloader-dot-loading">
                        <div class="cssload-loading"><i></i><i></i><i></i><i></i></div>
                    </div>
                </div>
                <div id="disable-preloader" class="btn btn-default btn-sm">Disable Preloader</div>
            </div>*@

        <!-- Header -->
        @Html.Partial("_PartialHeaderKH")

        <!-- Start main-content -->
        @RenderBody()

        <!-- Footer -->
        @Html.Partial("_PartialFooter")
        <a class="scrollToTop" href="#"><i class="fa fa-angle-up"></i></a>
    </div>
    <!-- end wrapper -->
    <!-- Footer Scripts -->
    <!-- JS | Custom script for all pages -->
    <script src="~/Content/js/custom.js"></script>

    <!-- SLIDER REVOLUTION 5.0 EXTENSIONS
        (Load Extensions only on Local File Systems !The following part can be removed on Server for On Demand Loading) -->
    <script type="text/javascript" src="~/Content/js/revolution-slider/js/extensions/revolution.extension.actions.min.js"></script>
    <script type="text/javascript" src="~/Content/js/revolution-slider/js/extensions/revolution.extension.carousel.min.js"></script>
    <script type="text/javascript" src="~/Content/js/revolution-slider/js/extensions/revolution.extension.kenburn.min.js"></script>
    <script type="text/javascript" src="~/Content/js/revolution-slider/js/extensions/revolution.extension.layeranimation.min.js"></script>
    <script type="text/javascript" src="~/Content/js/revolution-slider/js/extensions/revolution.extension.migration.min.js"></script>
    <script type="text/javascript" src="~/Content/js/revolution-slider/js/extensions/revolution.extension.navigation.min.js"></script>
    <script type="text/javascript" src="~/Content/js/revolution-slider/js/extensions/revolution.extension.parallax.min.js"></script>
    <script type="text/javascript" src="~/Content/js/revolution-slider/js/extensions/revolution.extension.slideanims.min.js"></script>
    <script type="text/javascript" src="~/Content/js/revolution-slider/js/extensions/revolution.extension.video.min.js"></script>
    <script src="~/Content/js/bootstrap-rating/bootstrap-rating.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ELearning/Source/ELearning/Views/Shared/_PartialFooter.cshtml
@*@using ELearning.Handler*@
<footer>
        <div class="quick-click">
            <div class="quick-link">
                <a href="~/Home/Home"><img src="~/Content/img/Home/logo.png" id="logo2"></a>
                <p>
                    CodeAmaz là nền tảng học lập trình trực tuyến,<br />hỗ trợ người dùng trong quá trình tự học<br />một cách chính xác và nhanh chóng.
                </p>
            </div>
            <div class="quick-link">
                <h2 class="title-end">Liên kết</h2>
                <p>@Html.ActionLink("Khóa Học", "Index", "Course")</p>
                <p>@Html.ActionLink("Blog", "Home", "Blog")</p>
            </div>
            <div class="quick-link">
                <h2 class="title-end">Thông tin</h2>
                <p>@Html.ActionLink("Thông Tin CodeAmaz", "About", "Home")</p>
            </div>
            <div class="quick-link">
                <h2 class="title-end">Trợ giúp</h2>
                <p>@Html.ActionLink("Liên Hệ CodeAmaz", "Contact", "Home")</p>
            </div>
        </div>

        <div id="endpage">
            ❤️ &copy; @DateTime.Now.Year - Website design by HUTECH TEAM ❤️
        </div>

    </footer>
@*@using ELearning.Handler
<footer id="footer" class="footer divider layer-overlay overlay-dark-9" data-bg-img="/Content/images/bg/bg2.jpg">
    <div class="container">
        <div class="row border-bottom">
            <div class="col-sm-6 col-md-3">
                <div class="widget dark">
                    <img class="mt-5 mb-20" alt="" src="~/Content/images/logo-white-footer.png">
                    <p>203, Envato Labs, Behind Alis Steet, Melbourne, Australia.</p>
                    <ul class="list-inline mt-5">
                        <li class="m-0 pl-10 pr-10">
                            <i class="fa fa-phone text-theme-color-2 mr-5"></i> <a class="text-gray"
                                                                                   href="#">123-456-789</a>
                        </li>
                        <li class="m-0 pl-10 pr-10">
                            <i class="fa fa-envelope-o text-theme-color-2 mr-5"></i> <a class="text-gray" href="#">contact@yourdomain.com</a>
                        </li>
                        <li class="m-0 pl-10 pr-10">
                            <i class="fa fa-globe text-theme-color-2 mr-5"></i> <a class="text-gray"
                                                                                   href="#">www.yourdomain.com</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-6 col-md-3">
                <div class="widget dark">
                    <h4 class="widget-title">@L.T("UsefulLink")</h4>
                    <ul class="list angle-double-right list-border">
                        <li><a href="page-about-style1.html">@L.T("AboutUs")</a></li>
                        <li><a href="page-course-list.html">@L.T("OurCourse")</a></li>
                        <li><a href="page-pricing-style1.html">Pricing Table</a></li>
                        <li><a href="page-gallery-3col.html">Gallery</a></li>
                        <li><a href="shop-category.html">Shop</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-6 col-md-3">

            </div>
            <div class="col-sm-6 col-md-3">
                <div class="widget dark">
                    <h4 class="widget-title line-bottom-theme-colored-2">@L.T("OpeningHour")</h4>
                    <div class="opening-hours">
                        <ul class="list-border">
                            <li class="clearfix">
                                <span> Mon - Tues : </span>
                                <div class="value pull-right"> 6.00 am - 10.00 pm </div>
                            </li>
                            <li class="clearfix">
                                <span> Wednes - Thurs :</span>
                                <div class="value pull-right"> 8.00 am - 6.00 pm </div>
                            </li>
                            <li class="clearfix">
                                <span> Fri : </span>
                                <div class="value pull-right"> 3.00 pm - 8.00 pm </div>
                            </li>
                            <li class="clearfix">
                                <span> Sun : </span>
                                <div class="value pull-right"> Closed </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-30">
            <div class="col-md-2">

            </div>
            <div class="col-md-3">

            </div>
            <div class="col-md-5 col-md-offset-2">

            </div>
        </div>
    </div>

</footer>*@

ELearning/Source/ELearning/Views/Shared/_PartialHeader.cshtml
@using ELearning.Handler
@using BELibrary.Utils
@{
    string urlFlag = "/Content/images/flags/" + CookiesManage.GetLanguageCode() + ".png";
    <link href="~/Content/css/TrangChu.css" rel="stylesheet" />
}
<header id="header" class="header">
    <div class="header-nav">
		<div class="header-nav-wrapper navbar-scrolltofixed bg-theme-colored border-bottom-theme-color-2-1px">
			<a href="/"><img src="~/Content/images/logo.png" id="logo1" /></a>
			<div class="container">
				<nav id="menuzord" class="menuzord bg-theme-colored pull-left flip menuzord-responsive">
					<ul class="menuzord-menu">
						<li id="tab-tab-hihi"></li>
						<li class="active">
							<a href="/">@L.T("Home")</a>
						</li>
						<li>
							<a href="/course">@L.T("Course")</a>
						</li>
						<li><a href="~/Blog/Home">Blog</a></li>
						<li>
							<a href="/Home/About">@L.T("AboutUs")</a>
						</li>
						<li><a href="~/Home/Contact">Liên hệ</a></li>
						<li>
							<a href="javascript:void(0);">
								<img src="@urlFlag" style="border:solid 1px #5f5d5a9e" />
							</a>
						</li>
						<li class="text-white">|</li>
						@if (CookiesManage.Logined())
						{
							<li>
								<a class="text-white" href="/account">@CookiesManage.GetUser().FullName</a>
							</li>
							<li class="text-white">|</li>
							<li>
								<a class="text-white" href="/account/logout">@L.T("Logout")</a>
							</li>
						}
						else
						{
							<li>
								<a style="margin-left:10px" href="/account/login">@L.T("Login")</a>
							</li>
							<li>
								<a href="/admin">@L.T("LoginAdmin")</a>
							</li>
						}
					</ul>
					<div id="top-search-bar" class="collapse">
						<div class="container">
							<form role="search" action="#" class="search_form_top" method="get">
								<input type="text" placeholder="Type text and press Enter..." name="s" class="form-control"
									   autocomplete="off">
								<span class="search-close"><i class="fa fa-search"></i></span>
							</form>
						</div>
					</div>
				</nav>
			</div>
		</div>
    </div>
</header>

ELearning/Source/ELearning/Views/Shared/_PartialHeaderKH.cshtml
@using ELearning.Handler
@using BELibrary.Utils
@{
    string urlFlag = "/Content/images/flags/" + CookiesManage.GetLanguageCode() + ".png";
    <link href="~/Content/css/TrangChu.css" rel="stylesheet" />
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" type="text/css">

}
<header id="header" class="header">
    <div class="header-nav">
        <div class="header-nav-wrapper navbar-scrolltofixed bg-theme-colored border-bottom-theme-color-2-1px">
            <div class="container">

                <nav id="menuzord" class="menuzord bg-theme-colored pull-left flip menuzord-responsive">
                    <ul class="menuzord-menu">
                        <li><a href="~/Home/Index"><img src="~/Content/images/logo.png" id="logo1"></a></li>
                        <li class="active">
                            <a href="/">@L.T("Home")</a>
                        </li>
                        <li>
                            <a href="#home">@L.T("Course")</a>
                            <ul class="dropdown">
                                <li><a href="/course">@L.T("CourseList")</a></li>
                                <li><a href="/subject">@L.T("SubjectList")</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="/Home/About">@L.T("AboutUs")</a>
                        </li>
                        <li><a href="~/Blog/Home">Blog</a></li>
                        <li><a href="~/Home/Contact">Liên hệ</a></li>
                        <li>
                            <a href="javascript:void(0);">
                                <img src="@urlFlag" style="border:solid 1px #5f5d5a9e" />
                            </a>
                            <ul class="dropdown">
                                <li>
                                    <a href="~/Home/SetLanguage?code=en">
                                        <img src="~/Content/images/flags/en.png" />
                                        <span class="flags-text">English</span>
                                    </a>
                                </li>
                                <li>

                                </li>
                                <li>
                                    <a href="~/Home/SetLanguage?code=vi">
                                        <img src="~/Content/images/flags/vi.png" />
                                        <span class="flags-text">Việt Nam</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="text-white">|</li>
                        @if (CookiesManage.Logined())
                        {
                            <li>
                                <a class="text-white" href="/account">@CookiesManage.GetUser().FullName</a>
                            </li>
                            <li class="text-white">|</li>
                            <li>
                                <a class="text-white" href="/account/logout">@L.T("Logout")</a>
                            </li>
                        }
                        else
                        {
                            <li>
                                <a class="text-white" href="/account/login">@L.T("Login")</a>
                            </li>
                        }
                    </ul>
                    <div id="top-search-bar" class="collapse">
                        <div class="container">
                            <form role="search" action="#" class="search_form_top" method="get">
                                <input type="text" placeholder="Type text and press Enter..." name="s" class="form-control"
                                       autocomplete="off">
                                <span class="search-close"><i class="fa fa-search"></i></span>
                            </form>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>