ELearning/Source/ELearning/Areas/Admin/Controllers/MLectureController.cs
using BELibrary.Core.Entity;
using BELibrary.Entity;
using System;
using System.Linq;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using BELibrary.Utils;

namespace ELearning.Areas.Admin.Controllers
{
    public class MLectureController : BaseController
    {
        private readonly string keyElement = "Bài học";

        public ActionResult Index()
        {
            ViewBag.Element = keyElement;

            var user = GetCurrentUser();
            using (var workScope = new UnitOfWork(new ELearningDBContext()))
            {
                switch (user.RoleId)
                {
                    case RoleKey.Teacher:
                        {
                            //Lấy danh sách môn học đc giao của giáo viên
                            var subjectAssign =
                                workScope.TeacherSubjects.Query(x => x.Username.ToLower() == user.Username.ToLower());

                            //Join bảng môn học và môn học được giao của giáo viên đang đăng nhập
                            var subjects = workScope.Subjects.GetAll().Join(
                                subjectAssign,
                                sj => sj.Id,
                                sja => sja.SubjectId,
                                (sj, sja) => new { sj }).Select(x => x.sj).Where(x => x.Status).ToList();

                            var listData = workScope.Lectures.Include(x => x.Subject).Join(
                                subjects,
                                lt => lt.SubjectId,
                                sj => sj.Id,
                                (lt, sj) => new { lt }).Select(x => x.lt).ToList();

                            return View(listData);
                        }
                    case RoleKey.Admin:
                        {
                            var listData = workScope.Lectures.Include(x => x.Subject).ToList();
                            return View(listData);
                        }
                    default:
                        return RedirectToAction("E401", "Dashboard");
                }
            }
        }

        public ActionResult Create()
        {
            ViewBag.key = "Thêm mới";
            ViewBag.Element = keyElement;

            ViewBag.isEdit = false;

            using (var workScope = new UnitOfWork(new ELearningDBContext()))
            {
                var user = GetCurrentUser();

                switch (user.RoleId)
                {
                    case RoleKey.Teacher:
                        {
                            //Lấy danh sách môn học đc giao của giáo viên
                            var subjectAssign =
                                workScope.TeacherSubjects.Query(x => x.Username.ToLower() == user.Username.ToLower());

                            //Join bảng môn học và môn học được giao của giáo viên đang đăng nhập
                            var subject = workScope.Subjects.GetAll().Join(
                                subjectAssign,
                                sj => sj.Id,
                                sja => sja.SubjectId,
                                (sj, sja) => new { sj }).Select(x => x.sj).Where(x => x.Status).ToList();

                            ViewBag.Subject = new SelectList(subject, "Id", "Name");
                            break;
                        }
                    case RoleKey.Admin:
                        {
                            var subject = workScope.Subjects.Query(x => x.Status).ToList();

                            ViewBag.Subject = new SelectList(subject, "Id", "Name");
                            break;
                        }
                    default:
                        return RedirectToAction("E401", "Dashboard");
                }
            }

            return View();
        }

        public ActionResult Update(int id)
        {
            ViewBag.isEdit = true;
            ViewBag.key = "Cập nhật";
            ViewBag.Element = keyElement;
            using (var workScope = new UnitOfWork(new ELearningDBContext()))
            {
                var lecture = workScope.Lectures.FirstOrDefault(x => x.Id == id);
                var user = GetCurrentUser();
                switch (user.RoleId)
                {
                    case RoleKey.Teacher:
                        {
                            var subjectAssign =
                                workScope.TeacherSubjects.Query(x => x.Username.ToLower() == user.Username.ToLower());

                            var subjects = workScope.Subjects.GetAll().Join(
                                subjectAssign,
                                sj => sj.Id,
                                sja => sja.SubjectId,
                                (sj, sja) => new { sj }).Select(x => x.sj).Where(x => x.Status).ToList();

                            if (subjects.Any(x => x.Id != lecture.SubjectId))
                            {
                                return RedirectToAction("E401", "Dashboard");
                            }

                            ViewBag.Subject = new SelectList(subjects, "Id", "Name");

                            break;
                        }
                    case RoleKey.Admin:
                        {
                            var subject = workScope.Subjects.Query(x => x.Status).ToList();

                            ViewBag.Subject = new SelectList(subject, "Id", "Name");
                            break;
                        }
                    default:
                        return RedirectToAction("E401", "Dashboard");
                }

                return View("Create", lecture);
            }
        }

        [HttpPost, ValidateInput(false)]
        public JsonResult CreateOrEdit(Lecture input, bool isEdit)
        {
            var user = GetCurrentUser();
            try
            {
                if (isEdit) //update
                {
                    using (var workScope = new UnitOfWork(new ELearningDBContext()))
                    {
                        //Check quyền
                        var elm = workScope.Lectures.Get(input.Id);

                        switch (user.RoleId)
                        {
                            case RoleKey.Teacher:
                                {
                                    var subjectAssign =
                                        workScope.TeacherSubjects.Query(x => x.Username.ToLower() == user.Username.ToLower());

                                    var subjects = workScope.Subjects.GetAll().Join(
                                        subjectAssign,
                                        sj => sj.Id,
                                        sja => sja.SubjectId,
                                        (sj, sja) => new { sj }).Select(x => x.sj).Where(x => x.Status).ToList();

                                    if (subjects.Any(x => x.Id != elm.SubjectId))
                                    {
                                        return Json(new { status = false, mess = "Không có quyền " });
                                    }

                                    break;
                                }
                            case RoleKey.Admin:
                                {
                                    break;
                                }
                            default:
                                return Json(new { status = false, mess = "Không có quyền " });
                        }

                        if (elm != null) //update
                        {
                            input.CreatedBy = elm.CreatedBy;
                            input.CreatedDate = elm.CreatedDate;
                            elm = input;
                            elm.ModifiedBy = GetCurrentUser().FullName;
                            elm.ModifiedDate = DateTime.Now;
                            workScope.Lectures.Put(elm, elm.Id);
                            workScope.Complete();
                            return Json(new { status = true, mess = "Cập nhập thành công" });
                        }
                        else
                        {
                            return Json(new { status = false, mess = "Không tồn tại " + keyElement });
                        }
                    }
                }
                else
                {
                    using (var workScope = new UnitOfWork(new ELearningDBContext()))
                    {
                        input.CreatedBy = GetCurrentUser().FullName;
                        input.CreatedDate = DateTime.Now;
                        input.ModifiedBy = GetCurrentUser().FullName;
                        input.ModifiedDate = DateTime.Now;

                        switch (user.RoleId)
                        {
                            case RoleKey.Teacher:
                                {
                                    var subjectAssign =
                                        workScope.TeacherSubjects.Query(x => x.Username.ToLower() == user.Username.ToLower());

                                    var subjects = workScope.Subjects.GetAll().Join(
                                        subjectAssign,
                                        sj => sj.Id,
                                        sja => sja.SubjectId,
                                        (sj, sja) => new { sj }).Select(x => x.sj).Where(x => x.Status).ToList();

                                    if (subjects.Any(x => x.Id != input.SubjectId))
                                    {
                                        return Json(new { status = false, mess = "Không có quyền " });
                                    }
                                    break;
                                }
                            case RoleKey.Admin:
                                {
                                    break;
                                }

ELearning/Source/ELearning/Areas/Admin/Controllers/MTestController.cs
using BELibrary.Core.Entity;
using BELibrary.Entity;
using System;
using System.Linq;
using System.Web.Mvc;
using BELibrary.Utils;

namespace ELearning.Areas.Admin.Controllers
{
    public class MTestController : BaseController
    {
        private readonly string keyElement = "Kiểm tra";

        public ActionResult Index(int lectureId)
        {
            ViewBag.Element = keyElement;
            using (var workScope = new UnitOfWork(new ELearningDBContext()))
            {
                var user = GetCurrentUser();
                if (user.RoleId == RoleKey.Admin)
                {
                    var listData = workScope.StudentTests.Include(x => x.User).Where(x => x.LectureId == lectureId).ToList();
                    return View(listData);
                }
                else
                {
                    var subjectAssign =
                        workScope.TeacherSubjects.Query(x => x.Username.ToLower() == user.Username.ToLower());

                    var subjects = workScope.Subjects.GetAll().Join(
                        subjectAssign,
                        sj => sj.Id,
                        sja => sja.SubjectId,
                        (sj, sja) => new { sj }).Select(x => x.sj).Where(x => x.Status).ToList();

                    var lectures = workScope.Lectures.GetAll().Join(
                        subjects,
                        l => l.SubjectId,
                        sj => sj.Id,
                        (l, sj) => new { l }).Select(x => x.l).ToList();

                    var studentTests = workScope.StudentTests.GetAll().Join(
                        lectures,
                        st => st.LectureId,
                        l => l.Id,
                        (st, l) => new { st }).Select(x => x.st).ToList();

                    return View(studentTests);
                }
            }
        }

        public ActionResult Update(int id)
        {
            ViewBag.isEdit = true;
            ViewBag.key = "Cập nhật";
            ViewBag.Element = keyElement;
            using (var workScope = new UnitOfWork(new ELearningDBContext()))
            {
                var user = GetCurrentUser();
                if (user.RoleId == RoleKey.Admin)
                {
                    var student = workScope.StudentTests.FirstOrDefault(x => x.Id == id);

                    return View(student);
                }
                else
                {
                    var subjectAssign =
                        workScope.TeacherSubjects.Query(x => x.Username.ToLower() == user.Username.ToLower());

                    var subjects = workScope.Subjects.GetAll().Join(
                        subjectAssign,
                        sj => sj.Id,
                        sja => sja.SubjectId,
                        (sj, sja) => new { sj }).Select(x => x.sj).Where(x => x.Status).ToList();

                    var lectures = workScope.Lectures.GetAll().Join(
                        subjects,
                        l => l.SubjectId,
                        sj => sj.Id,
                        (l, sj) => new { l }).Select(x => x.l).ToList();

                    var studentTests = workScope.StudentTests.GetAll().Join(
                        lectures,
                        st => st.LectureId,
                        l => l.Id,
                        (st, l) => new { st }).Select(x => x.st);

                    var studentTest = studentTests.FirstOrDefault(x => x.Id == id);

                    if (studentTest == null)
                    {
                        return RedirectToAction("E401", "Dashboard");
                    }
                    return View(studentTest);
                }
            }
        }

        [HttpPost, ValidateInput(false)]
        public JsonResult CreateOrEdit(StudentTest input, bool isEdit)
        {
            try
            {
                if (!isEdit) return Json(new { status = false, mess = "Có lỗi xảy ra: " });
                using (var workScope = new UnitOfWork(new ELearningDBContext()))
                {
                    var elm = workScope.StudentTests.Get(input.Id);
                    if (elm != null) //update
                    {
                        elm.Point = input.Point;
                        elm.ReplyFile = input.ReplyFile;

                        workScope.StudentTests.Put(elm, elm.Id);
                        workScope.Complete();
                        return Json(new { status = true, mess = "Cập nhập thành công" });
                    }
                    else
                    {
                        return Json(new { status = false, mess = "Không tồn tại " + keyElement });
                    }
                }
            }
            catch (Exception ex)
            {
                return Json(new { status = false, mess = "Có lỗi xảy ra: " + ex.Message });
            }
        }

        [HttpPost]
        public JsonResult Del(int id)
        {
            try
            {
                using (var workScope = new UnitOfWork(new ELearningDBContext()))
                {
                    var elm = workScope.StudentTests.Get(id);
                    if (elm != null) //update
                    {
                        workScope.StudentTests.Remove(elm);
                        workScope.Complete();
                        return Json(new { status = true, mess = "Xóa thành công " + keyElement });
                    }
                    else
                    {
                        return Json(new { status = false, mess = "Không tồn tại " + keyElement });
                    }
                }
            }
            catch
            {
                return Json(new { status = false, mess = "Thất bại" });
            }
        }
    }
}

ELearning/Source/ELearning/Areas/Admin/Views/MTest/Index.cshtml
@using BELibrary.Entity
@using BELibrary.Utils
@model List<StudentTest>
@{
    ViewBag.Title = "Quản lý " + ViewBag.Element;
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

}

<div id="page-title">
    <h5 class="text-overflow">Danh sách @ViewBag.Element</h5>
    <!--Searchbox-->
    <div class="searchbox">
        <div class="input-group custom-search-form">
            <input type="text" class="form-control" placeholder="Search..">
            <span class="input-group-btn">
                <button class="text-muted" type="button"><i class="fa fa-search"></i></button>
            </span>
        </div>
    </div>
</div>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<ol class="breadcrumb">
    <li><a href="/Admin">Admin</a></li>
    <li class="">@ViewBag.Element</li>
    <li class="active">Danh sách</li>
</ol>
<!--End breadcrumb-->
<!--Page content-->
<!--===================================================-->
<div id="page-content">
    <!--Product table-->
    <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
    <div>
        <div class="panel">
            <div class="panel-body">
                <div class="pad-btm form-inline">
                    <div class="row">
                        <div class="col-sm-6 table-toolbar-left">
                            <a href="@Url.Action("Create", "MLecture")" disabled
                               class="btn btn-purple btn-labeled fa fa-plus">Thêm @ViewBag.Element</a>
                        </div>
                        <div class="col-sm-6 table-toolbar-right">
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped table-hover" id="tableData">
                        <thead>
                            <tr>
                                <th class="text-center">ID</th>
                                <th class="text-center">Học viên</th>
                                <th class="text-center">Trạng thái</th>
                                <th class="text-center">Tải file</th>
								<th class="text-center">Thao tác</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr class="odd gradeX" id="row_@item.Id">
                                    <td class="text-center"><a href="/admin/msubject/update?id=@item.Id">@item.Id</a></td>
                                    <td class="text-center">@item.User.FullName</td>
                                    @if (item.Status)
                                    {
                                        <td class="text-center"><span class="badge badge-success">Đã duyệt </span></td>
                                    }
                                    else
                                    {
                                        <td class="text-center"><span class="badge badge-warning">Đang chờ</span></td>

                                    }
                                    <td class="text-center"><a href="@item.FileAnswer" class="btn btn-success"><i class="fa fa-download"></i></a></td>
                                    <td class="text-center td-action">
                                        <a class="btn btn-xs btn-default add-tooltip"
                                           data-toggle="tooltip"
                                           data-original-title="Cập nhật kiểm tra"
                                           data-container="body"
                                           href="/admin/mtest/update?id=@item.Id">
                                            <i class="fa fa-pencil"></i>
                                        </a>
                                        <a class="btn btn-xs btn-danger add-tooltip"
                                           data-toggle="tooltip"
                                           data-original-title="Xóa bài kt"
                                           data-container="body"
                                           href="javascript:void(0)" onclick="del('@item.Id', '@item.User.FullName')">
                                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!--Bootbox Modals [ OPTIONAL ]-->
    <script src="~/Areas/Admin/lib/plugins/bootbox/bootbox.min.js"></script>
    <!--Modals [ SAMPLE ]-->
    <!--End user table-->
</div>
<!--===================================================-->
<!--End page content-->
@section Scripts {
    <script>
        $(document).ready(function () {
            $('#tableData').DataTable();
        });

        function del(id, name) {
            var mess = 'Xác nhận <b>xóa</b> bản ghi <b>' + name + '</b>';
            bootbox.confirm(mess, function (result) {
                if (result) {
                    delPost(id)
                }
            });
        }
        function secondsToHms(d) {
            d = Number(d);
            var h = Math.floor(d / 3600);
            var m = Math.floor(d % 3600 / 60);
            var s = Math.floor(d % 3600 % 60);

            var hDisplay = h > 0 ? h + (h == 1 ? " hour, " : " hours, ") : "";
            var mDisplay = m > 0 ? m + (m == 1 ? " minute, " : " minutes, ") : "";
            var sDisplay = s > 0 ? s + (s == 1 ? " second" : " seconds") : "";
            return hDisplay + mDisplay + sDisplay;
        }
        function delPost(id) {
            $.ajax({
                type: 'POST',
                url: '/admin/mlecture/del',
                dataType: 'json',
                data: { id: id },
                success: function (response) {
                    if (response.status) {
                        $.niftyNoty({
                            type: 'success',
                            icon: 'fa fa-check',
                            message: response.mess,
                            container: 'floating',
                            timer: 3000
                        });
                        $("#row_" + id).remove();
                    } else {
                        $.niftyNoty({
                            type: 'danger',
                            icon: 'fa fa-minus',
                            message: response.mess,
                            container: 'floating',
                            timer: 3000
                        });
                    }

                },
                error: function (jqXHR) {
                    $.niftyNoty({
                        type: 'success',
                        icon: 'fa fa-check',
                        message: 'User confirmed dialog',
                        container: 'floating',
                        timer: 3000
                    });

                }
            });
        };
    </script>
}

ELearning/Source/ELearning/Areas/Admin/Views/MTest/Update.cshtml
@using System.Web.Mvc
@using BELibrary.Entity
@model StudentTest
@{
    ViewBag.Title = ViewBag.Key + " " + ViewBag.Element;
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var isSendMail = true;
}
<style>
    .display-none {
        display: none;
    }

    .display-block {
        display: block;
    }
</style>
<div id="page-title">
    <h5 class="text-overflow">@ViewBag.Key @ViewBag.Element</h5>
    <!--Searchbox-->
    <div class="searchbox">
        <div class="input-group custom-search-form">
            <input type="text" class="form-control" placeholder="Search..">
            <span class="input-group-btn">
                <button class="text-muted" type="button"><i class="fa fa-search"></i></button>
            </span>
        </div>
    </div>
</div>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<ol class="breadcrumb">
    <li><a href="/admin">Admin</a></li>
    <li><a href="/admin/mlecture">@ViewBag.Element</a></li>
    <li class="active">@ViewBag.Key @ViewBag.Element</li>
</ol>
<!--End breadcrumb-->
<!--Page content-->
<!--===================================================-->
<div id="page-content">
    <ul class="nav nav-tabs">
        <li class="active">
            <a data-toggle="tab" href="product_add#post">Bài viết </a>
        </li>
    </ul>
    <!--Tabs Content-->

    <form id="form">
        <div class="tab-content">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @if (ViewBag.isEdit)
            {
                <input type="hidden" value="true" name="isEdit" />
                <input type="hidden" value="@Model.Id" name="Id" />
            }
            else
            {
                <input type="hidden" value="false" name="isEdit" />
            }
            <div id="post" class="tab-pane fade active in">
                <div class="panel">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label class="control-label">Gửi mail</label>
                                    @Html.CheckBoxFor(model => isSendMail, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label class="control-label">Điểm</label>
                                    @Html.EditorFor(model => model.Point, new { htmlAttributes = new { @class = "form-control", @required = "required", type = "Number" } })
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="form-group">
                                    <label class="control-label">File kết quả</label>
                                    <div class="input-group date">
                                        @Html.EditorFor(model => model.ReplyFile, new { htmlAttributes = new { @class = "form-control", @required = "required", @maxlength = 250 } })
                                        <span class="input-group-addon" onclick="ReplyFile()">
                                            <i class="fa fa-upload fa-lg"></i>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-6">
                                <a class="btn btn-default btn-icon icon-lg fa fa-arrow-left fa-lg" href="/admin/mlecture"></a>
                            </div>
                            <div class="col-sm-6">
                                <button class="btn btn-success btn-labeled fa fa-send fa-lg btn-save" style="float: right;" type="submit">Save</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

@section Scripts {

    <script>
        $(document).ready(function () {
        });

        function ReplyFile() {
            const finder = new CKFinder();
            finder.selectActionFunction = function (fileUrl) {
                $("#ReplyFile").val(fileUrl);
            }
            finder.popup();
        }

        $('#form')
            .submit(function (e) {
                e.preventDefault();
                var formData = new FormData(this);
                $.ajax({
                    url: '/admin/mtest/CreateOrEdit',
                    type: 'POST',
                    data: formData,
                    success: function (response) {
                        if (response.status) {
                            $.niftyNoty({
                                type: 'success',
                                icon: 'fa fa-check',
                                message: response.mess,
                                container: 'floating',
                                timer: 3000
                            });
                            setTimeout(function () {
                                window.location.reload();
                            }, 3000);
                        } else {
                            $.niftyNoty({
                                type: 'danger',
                                icon: 'fa fa-minus',
                                message: response.mess,
                                container: 'floating',
                                timer: 3000
                            });
                            $(':input[type="submit"]').prop('disabled', false);
                        }
                    },
                    cache: false,
                    contentType: false,
                    processData: false
                });
            });
    </script>
}